export const types = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  CHECK_AUTH_REQUEST: "CHECK_AUTH_REQUEST",
  CHECK_AUTH_REQUEST_LOADING: "CHECK_AUTH_REQUEST_LOADING",
  LEADERBOARD_REQUEST: "LEADERBOARD_REQUEST",
  LEADERBOARD_REQUEST_LOADING: "LEADERBOARD_REQUEST_LOADING",
  SCORE_REQUEST: "SCORE_REQUEST",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
};
